project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Final Project by Yuanhao & Kay"
  site-url: "https://zhaiyuanhao.github.io/Final-Project-Yuanhao-Kay" 
  repo-url: https://github.com/zhaiyuanhao/Final-Project-Yuanhao-Kay
  repo-actions: [source]

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-Yuanhao Zhai, Kay Li, 2023"

  sidebar:
    logo: "images/housing-logo.png"
    pinned: true
    align: left
    tools: 
      - icon: github
        href: https://github.com/zhaiyuanhao/Final-Project-Yuanhao-Kay
        text: "Final Project GitHub"
   

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Project Introduction
      - about.qmd
      - href: analysis/Final_Assignment.ipynb
        text: Analysis Process


format:
  html:
    highlight-style: solarized
    theme: journal
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




